Revert "Enable nix-direnv"
Configuration causes error on NixOS systems.
  error: unexpected argument 'enableFlakes'

Return to old configuration awaiting further investigation.

This reverts commit 80e3d0e064fdc27527cc6e47a863b4368daf543f.